version: '3.1'

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
        # MONGO_INITDB_ROOT_USERNAME: adminCRM
        # MONGO_INITDB_ROOT_PASSWORD: cqs9crm
        MONGO_INITDB_DATABASE: api
  db-seed:
    build: ./mongo
    links:
      - db



    